global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receivers:
    - name: 'default'

groups:
  - name: Latency
    rules:
      - alert: LatencyOver300
        expr: current_response_time >= 300
        for: 5m
    receivers:
      - name: 'pagerduty'

  - name: PacketLoss
    rules:
      - alert: PacketLossOver40%
        expr: avg_over_time(check_request_failed[300s])>0.4
    receivers:
      - name: 'pagerduty'

receivers:
- name: 'default'
  email_configs:
  - to: 'defaultsupport@example.com'
- name: 'pagerduty'
  pagerduty_configs:
  - routing_key: xyz
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
